name: Sprites
version: '${pluginVersion}'
description: '${description}'
authors: [blablubbabc]
website: '${dboUrl}'
# Loading after world management plugins and soft dependencies:
softdepend: [Multiverse-Core, My Worlds, Transporter, Vault]

main: de.blablubbabc.sprites.SpritesPlugin
api-version: '1.21.4'

commands:
    sprite:
        description: TODO
        usage: 'Unknown command! Try /<command> help'
